/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Ventanas;

import Filtros.*;
import Sistema_Base.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Mainque
 */
public class Busqueda extends javax.swing.JFrame {
    
    //constructor
    public Busqueda() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Interfaz/Imagenes/icono v1.png"));
        return retValue;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jCheckBoxFTipo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBoxFPrecio = new javax.swing.JCheckBox();
        jTextFieldPrecioMin = new javax.swing.JTextField();
        jTextFieldPrecioMax = new javax.swing.JTextField();
        jCheckBoxFPago = new javax.swing.JCheckBox();
        jComboBoxPago = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxFZona = new javax.swing.JCheckBox();
        jComboBoxZona = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxFHabitaciones = new javax.swing.JCheckBox();
        jTextFieldHabitaciones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxFMetros = new javax.swing.JCheckBox();
        jTextFieldMetrosMin = new javax.swing.JTextField();
        jTextFieldMetrosMax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxFPatio = new javax.swing.JCheckBox();
        jCheckBoxPatio = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxFAmueblado = new javax.swing.JCheckBox();
        jCheckBoxAmueblado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxFDuenio = new javax.swing.JCheckBox();
        jTextFieldDuenio = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExit.setText("Salir");
        jButtonExit.setBorder(null);
        jButtonExit.setBorderPainted(false);
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 60, 20));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 211, 153));
        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jComboBoxTipo.setBackground(new java.awt.Color(0, 217, 153));
        jComboBoxTipo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alquiler", "Venta", "Residencia" }));
        jComboBoxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, -1));

        jCheckBoxFTipo.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFTipo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFTipo.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFTipo.setAlignmentY(0.0F);
        jCheckBoxFTipo.setBorder(null);
        jCheckBoxFTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFTipo.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFTipo.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFTipo.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 211, 153));
        jLabel8.setText("Precio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jCheckBoxFPrecio.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFPrecio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFPrecio.setAlignmentY(0.0F);
        jCheckBoxFPrecio.setBorder(null);
        jCheckBoxFPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFPrecio.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFPrecio.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFPrecio.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, 20));

        jTextFieldPrecioMin.setBackground(new java.awt.Color(0, 217, 153));
        jTextFieldPrecioMin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldPrecioMin.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecioMin.setText("Min");
        jTextFieldPrecioMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMinActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecioMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, -1));

        jTextFieldPrecioMax.setBackground(new java.awt.Color(0, 217, 153));
        jTextFieldPrecioMax.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldPrecioMax.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecioMax.setText("Max");
        jTextFieldPrecioMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecioMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, -1));

        jCheckBoxFPago.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFPago.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFPago.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFPago.setAlignmentY(0.0F);
        jCheckBoxFPago.setBorder(null);
        jCheckBoxFPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFPago.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFPago.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFPago.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFPagoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 40, 30));

        jComboBoxPago.setBackground(new java.awt.Color(0, 217, 153));
        jComboBoxPago.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxPago.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Por día", "Por semana" }));
        jComboBoxPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));
        jComboBoxPago.getAccessibleContext().setAccessibleName("");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 211, 153));
        jLabel7.setText("Zona");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 176, -1, 20));

        jCheckBoxFZona.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFZona.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFZona.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFZona.setAlignmentY(0.0F);
        jCheckBoxFZona.setBorder(null);
        jCheckBoxFZona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFZona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFZona.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFZona.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFZona.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFZona.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFZonaActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 40, 30));

        jComboBoxZona.setBackground(new java.awt.Color(0, 217, 153));
        jComboBoxZona.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxZona.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Semi-Centro", "Villa Italia", "Movediza" }));
        jComboBoxZona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBoxZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 211, 153));
        jLabel10.setText("Habitaciones");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        jCheckBoxFHabitaciones.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFHabitaciones.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFHabitaciones.setAlignmentY(0.0F);
        jCheckBoxFHabitaciones.setBorder(null);
        jCheckBoxFHabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFHabitaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFHabitaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFHabitaciones.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFHabitaciones.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFHabitaciones.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFHabitacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 40, 20));

        jTextFieldHabitaciones.setBackground(new java.awt.Color(0, 217, 153));
        jTextFieldHabitaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHabitacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 40, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 211, 153));
        jLabel6.setText("Metros cuadrados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jCheckBoxFMetros.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFMetros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFMetros.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFMetros.setAlignmentY(0.0F);
        jCheckBoxFMetros.setBorder(null);
        jCheckBoxFMetros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFMetros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFMetros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFMetros.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFMetros.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFMetros.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFMetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFMetrosActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFMetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 40, 30));

        jTextFieldMetrosMin.setBackground(new java.awt.Color(0, 217, 153));
        jTextFieldMetrosMin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldMetrosMin.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldMetrosMin.setText("Min");
        jTextFieldMetrosMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMetrosMinActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMetrosMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, 30));

        jTextFieldMetrosMax.setBackground(new java.awt.Color(0, 217, 153));
        jTextFieldMetrosMax.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldMetrosMax.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldMetrosMax.setText("Max");
        jTextFieldMetrosMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMetrosMaxActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMetrosMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 211, 153));
        jLabel9.setText("Tiene patio?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 336, -1, 30));

        jCheckBoxFPatio.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFPatio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFPatio.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFPatio.setAlignmentY(0.0F);
        jCheckBoxFPatio.setBorder(null);
        jCheckBoxFPatio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFPatio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFPatio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFPatio.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFPatio.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFPatio.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFPatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFPatioActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFPatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 40, 20));

        jCheckBoxPatio.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxPatio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxPatio.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxPatio.setAlignmentY(0.0F);
        jCheckBoxPatio.setBorder(null);
        jCheckBoxPatio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxPatio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxPatio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxPatio.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxPatio.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxPatio.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxPatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPatioActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxPatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 30, 20));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 211, 153));
        jLabel5.setText("Es amueblado?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 20));

        jCheckBoxFAmueblado.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFAmueblado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFAmueblado.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFAmueblado.setAlignmentY(0.0F);
        jCheckBoxFAmueblado.setBorder(null);
        jCheckBoxFAmueblado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFAmueblado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFAmueblado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFAmueblado.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFAmueblado.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFAmueblado.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFAmueblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFAmuebladoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFAmueblado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 40, 20));

        jCheckBoxAmueblado.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxAmueblado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxAmueblado.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxAmueblado.setAlignmentY(0.0F);
        jCheckBoxAmueblado.setBorder(null);
        jCheckBoxAmueblado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxAmueblado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxAmueblado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxAmueblado.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxAmueblado.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxAmueblado.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxAmueblado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAmuebladoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxAmueblado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 30, 20));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 211, 153));
        jLabel1.setText("Dueño");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 396, -1, 20));

        jCheckBoxFDuenio.setBackground(new java.awt.Color(0, 211, 153));
        jCheckBoxFDuenio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxFDuenio.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFDuenio.setAlignmentY(0.0F);
        jCheckBoxFDuenio.setBorder(null);
        jCheckBoxFDuenio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxFDuenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxFDuenio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxFDuenio.setMargin(new java.awt.Insets(2, 2, 10, 2));
        jCheckBoxFDuenio.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBoxFDuenio.setPreferredSize(new java.awt.Dimension(20, 20));
        jCheckBoxFDuenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFDuenioActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxFDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 40, 30));

        jTextFieldDuenio.setBackground(new java.awt.Color(0, 217, 153));
        jTextFieldDuenio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldDuenio.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDuenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuenioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 180, -1));

        jButtonFiltrar.setBackground(new java.awt.Color(0, 217, 153));
        jButtonFiltrar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButtonFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.setBorder(null);
        jButtonFiltrar.setBorderPainted(false);
        jButtonFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 90, 30));

        jButtonInfo.setBackground(new java.awt.Color(0, 217, 153));
        jButtonInfo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButtonInfo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonInfo.setText("?");
        jButtonInfo.setBorder(null);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 466, 30, -1));

        jButtonAtras.setBackground(new java.awt.Color(0, 217, 153));
        jButtonAtras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAtras.setText("Atras");
        jButtonAtras.setBorder(null);
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 40, 20));

        jLabelFondo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        //Primero creamos los filtros para cada opcion seleccionada y la agregamos a una lista de filtros
        ArrayList<Filtro> filtros = new ArrayList<Filtro>();
        boolean errorNumero = false; //Boleano para detectar que un campo numerico tiene otros caracteres
        boolean errorVacio = false; //Boleano para detectar que un campo seleccionado esta vacio
        
        if (jCheckBoxFTipo.isSelected()){
            FiltroTipo f = new FiltroTipo(jComboBoxTipo.getSelectedItem().toString());
            filtros.add(f);
        }
        
        if (jCheckBoxFPrecio.isSelected()){
            if( !(jTextFieldPrecioMin.getText().isEmpty()) && !(jTextFieldPrecioMax.getText().isEmpty()) ){
                String p1 = jTextFieldPrecioMin.getText().strip();
                String p2 = jTextFieldPrecioMax.getText().strip();
                if(p1.matches("[+-]?\\d*(\\.\\d+)?") && p2.matches("[+-]?\\d*(\\.\\d+)?")){
                    FiltroRangoPrecio f = new FiltroRangoPrecio(Integer.valueOf(p1), Integer.valueOf(p2));
                    filtros.add(f);
                }else{
                    errorNumero = true;
                }
            }else{
                errorVacio = true;
            }
        }

        if (jCheckBoxFPago.isSelected()){
            FiltroPago f = new FiltroPago(jComboBoxPago.getSelectedItem().toString());
            filtros.add(f);
        }
        
        if (jCheckBoxFZona.isSelected()){
            FiltroZona f = new FiltroZona(jComboBoxZona.getSelectedItem().toString());
            filtros.add(f);
        }
        
        if (jCheckBoxFHabitaciones.isSelected()){
            if( !jTextFieldHabitaciones.getText().isEmpty() ){
                String h = jTextFieldHabitaciones.getText().strip();
                if( h.matches("[+-]?\\d*(\\.\\d+)?") ){
                    FiltroHabitaciones f = new FiltroHabitaciones(Integer.valueOf(h));
                    filtros.add(f);
                }else{
                    errorNumero= true;
                }
            }else{
                errorVacio= true;
            }
        }
        
        if (jCheckBoxFMetros.isSelected()){
            if( !(jTextFieldMetrosMin.getText().isEmpty()) && !(jTextFieldMetrosMax.getText().isEmpty()) ){
                String m1 = jTextFieldMetrosMin.getText().strip();
                String m2 = jTextFieldMetrosMax.getText().strip();
                if(m1.matches("[+-]?\\d*(\\.\\d+)?") && m2.matches("[+-]?\\d*(\\.\\d+)?")){
                    FiltroRangoTamanio f = new FiltroRangoTamanio(Integer.valueOf(m1), Integer.valueOf(m2));
                    filtros.add(f);
                }else{
                    errorNumero = true;
                }
            }else{
                errorVacio = true;
            }
        }
        
        if (jCheckBoxFPatio.isSelected()){
            FiltroPatio f = new FiltroPatio(jCheckBoxPatio.isSelected());
            filtros.add(f);
        }
        
        if (jCheckBoxFAmueblado.isSelected()){
            FiltroAmueblado f = new FiltroAmueblado(jCheckBoxAmueblado.isSelected());
            filtros.add(f);
        }
        
        if (jCheckBoxFDuenio.isSelected()){
            if( !jTextFieldDuenio.getText().isEmpty() ){
                FiltroDuenio f = new FiltroDuenio(jTextFieldDuenio.getText().strip());
                filtros.add(f);
            }else{
                errorVacio= true;
            }
        }
        
        if(errorNumero)
            JOptionPane.showMessageDialog(null, "Los campos numericos solo deben tener números.");
        if(errorVacio)
            JOptionPane.showMessageDialog(null, "Por favor, llenar los campos de las opciones seleccionadas para filtrar.");
        
        //Creamos el filtro final y buscamos en la lista de publicaciones
        if(!errorNumero && !errorVacio && !filtros.isEmpty()){
            ArrayList<Publicacion> resultado = new ArrayList<Publicacion>();
            Publicaciones listaP = new Publicaciones();
            if(filtros.size()==1){
                resultado= listaP.buscar(filtros.get(0));
            }else{//Tiene más de un filtro
                FiltroAnd fAnd = new FiltroAnd(filtros.get(0), filtros.get(1));
                for(int i=2; i<filtros.size(); i++){
                    fAnd = new FiltroAnd(fAnd, filtros.get(i));
                }
                resultado= listaP.buscar(fAnd);
            }
        }
        //TODO ver que hacer con resultado
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        Menu anterior = new Menu();
        anterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jTextFieldPrecioMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxActionPerformed

    private void jTextFieldMetrosMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMetrosMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMetrosMaxActionPerformed

    private void jComboBoxPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagoActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jCheckBoxAmuebladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAmuebladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAmuebladoActionPerformed

    private void jCheckBoxPatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPatioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPatioActionPerformed

    private void jTextFieldHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHabitacionesActionPerformed

    private void jTextFieldPrecioMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinActionPerformed

    private void jTextFieldDuenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuenioActionPerformed

    private void jTextFieldMetrosMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMetrosMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMetrosMinActionPerformed

    private void jCheckBoxFTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFTipoActionPerformed

    private void jCheckBoxFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFPrecioActionPerformed

    private void jCheckBoxFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFPagoActionPerformed

    private void jCheckBoxFZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFZonaActionPerformed

    private void jCheckBoxFHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFHabitacionesActionPerformed

    private void jCheckBoxFMetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFMetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFMetrosActionPerformed

    private void jCheckBoxFPatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFPatioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFPatioActionPerformed

    private void jCheckBoxFAmuebladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFAmuebladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFAmuebladoActionPerformed

    private void jCheckBoxFDuenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFDuenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFDuenioActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        JOptionPane.showMessageDialog(null, "Marque el cuadrado de aquellos campos por los que desea filtrar, luego complete el/los campo/s.");
    }//GEN-LAST:event_jButtonInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JCheckBox jCheckBoxAmueblado;
    private javax.swing.JCheckBox jCheckBoxFAmueblado;
    private javax.swing.JCheckBox jCheckBoxFDuenio;
    private javax.swing.JCheckBox jCheckBoxFHabitaciones;
    private javax.swing.JCheckBox jCheckBoxFMetros;
    private javax.swing.JCheckBox jCheckBoxFPago;
    private javax.swing.JCheckBox jCheckBoxFPatio;
    private javax.swing.JCheckBox jCheckBoxFPrecio;
    private javax.swing.JCheckBox jCheckBoxFTipo;
    private javax.swing.JCheckBox jCheckBoxFZona;
    private javax.swing.JCheckBox jCheckBoxPatio;
    private javax.swing.JComboBox<String> jComboBoxPago;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextFieldDuenio;
    private javax.swing.JTextField jTextFieldHabitaciones;
    private javax.swing.JTextField jTextFieldMetrosMax;
    private javax.swing.JTextField jTextFieldMetrosMin;
    private javax.swing.JTextField jTextFieldPrecioMax;
    private javax.swing.JTextField jTextFieldPrecioMin;
    // End of variables declaration//GEN-END:variables
}
