/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Ventanas;

import cl.pojos.Publicacion;
import cl.sistema.SistemaAplicacion;
import Filtros.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 * Clase para la interfaz de vista de las publicaciones del usuario actual (en esta misma puede eliminar las publicaciones que desee)
 * @author Mainque
 */
public class MisPublicaciones extends javax.swing.JFrame {
    private ArrayList<Publicacion> publicacionesDelUsuario;//Lista usada para mapear los strings de la lista con las publicaciones respectivas
    
    public MisPublicaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarJList();
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Interfaz/Imagenes/icono v1.png"));
        return retValue;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonVerMas = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListResult = new javax.swing.JList<>();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonExit.setText("Salir");
        jButtonExit.setBorder(null);
        jButtonExit.setBorderPainted(false);
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 60, 20));

        jButtonVerMas.setBackground(new java.awt.Color(0, 217, 153));
        jButtonVerMas.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonVerMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/icono v2.png"))); // NOI18N
        jButtonVerMas.setBorder(null);
        jButtonVerMas.setBorderPainted(false);
        jButtonVerMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVerMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 40, 30));

        jButtonAgregar.setBackground(new java.awt.Color(0, 217, 153));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jButtonAgregar.setText("+");
        jButtonAgregar.setBorder(null);
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 40, 30));

        jButtonBorrar.setBackground(new java.awt.Color(0, 217, 153));
        jButtonBorrar.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonBorrar.setText("-");
        jButtonBorrar.setBorder(null);
        jButtonBorrar.setBorderPainted(false);
        jButtonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 30));

        jButtonInfo.setBackground(new java.awt.Color(0, 217, 153));
        jButtonInfo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButtonInfo.setText("?");
        jButtonInfo.setBorder(null);
        jButtonInfo.setBorderPainted(false);
        jButtonInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 40, 30));

        jButtonMenu.setBackground(new java.awt.Color(0, 217, 153));
        jButtonMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonMenu.setText("Menú");
        jButtonMenu.setBorder(null);
        jButtonMenu.setBorderPainted(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 60, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 211, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Mis Publicaciones");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 420, 30));

        jListResult.setBackground(new java.awt.Color(0, 217, 153));
        jListResult.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jListResult.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 610, 400));

        jLabelFondo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/fondo.png"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 217, 153)));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int seleccionado = jListResult.getSelectedIndex();
        if(seleccionado!=-1){
            Publicacion p = this.publicacionesDelUsuario.get(seleccionado);//Obtengo la publicación seleccionada

            SistemaAplicacion sistema = new SistemaAplicacion();
            boolean seElimino= sistema.eliminarPublicacion(p, Login.getUsuarioActual());
            if(seElimino){
                JOptionPane.showMessageDialog(null, "Se eliminó la publicación correctamente.");
                cargarJList();
            }else{
                JOptionPane.showMessageDialog(null, "No se logró eliminar la publicación.");
                //Nunca se da este caso en un contexto sin errores
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar la publicación a eliminar."
                                          +"\n"+"     (Use el botón ? para saber más)");
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    //Limpia tanto la lista visual como el atributo contenedor
    private DefaultListModel limpiarJList(){
        this.publicacionesDelUsuario = new ArrayList<Publicacion>();
        DefaultListModel modelo = new DefaultListModel();
        jListResult.setModel(modelo);
        return modelo;
    }
    
    //Carga tanto la lista visual como el atributo contenedor
    private DefaultListModel cargarJList(){
        limpiarJList();
        
        SistemaAplicacion sistema = new SistemaAplicacion();
        this.publicacionesDelUsuario = sistema.buscar(new FiltroDuenio(Login.getUsuarioActual().getNombre()));
        
        DefaultListModel modelo = (DefaultListModel) jListResult.getModel();
        String piso;
        String depto;
        for(Publicacion p: publicacionesDelUsuario){
            piso = "";
            if(p.getPiso()>0)
                piso = ", piso " + String.valueOf(p.getPiso());
            depto = "";
            if(p.getDepto()>0)
                depto = ", depto " + String.valueOf(p.getDepto());
            modelo.addElement(p.toString() + piso + depto);//Añado a la lista
        }
        return modelo;
    }
    
    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        Menu anterior = new Menu();
        anterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        JOptionPane.showMessageDialog(null, "La lupa sirve para ver más sobre la publicación seleccionada, "
                                     +"\n"+ "El botón + permite añadir una nueva publicacion, "
                                     +"\n"+ "El botón - permite borrar la publicación seleccionada");
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        NuevaPublicacion siguiente = new NuevaPublicacion();
        siguiente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonVerMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMasActionPerformed
        int seleccionado = jListResult.getSelectedIndex();
        if(seleccionado!=-1){
            Publicacion p = this.publicacionesDelUsuario.get(seleccionado);//Obtengo la publicación seleccionada
            PublicacionDetallada pd = new PublicacionDetallada();
            pd.setPublicacion(p);
            pd.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar la publicación a mostrar."
                                          +"\n"+"    (Use el botón ? para saber más)");
        }
    }//GEN-LAST:event_jButtonVerMasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisPublicaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonVerMas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JList<String> jListResult;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
